### ISSUE TITLE
支持  tsx ？

### ISSUE THREAD

**Issue by scarcoco** [ThoughtWorksChina/taro-testing-library#1]
支持  tsx ？

**Comment by ariesjia** [comment]
配置ts-jest即可

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: scarcat <notifications@github.com>
发送时间: Tuesday, August 11, 2020 11:53:05 AM
收件人: ThoughtWorksChina/taro-testing-library <taro-testing-library@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [ThoughtWorksChina/taro-testing-library] 支持 tsx ？ (#1)


支持 tsx ？

―

**Comment by scarcoco** [comment]
babel 已经支持 ts 了，这个可以支持 snapshot Test？

**Comment by mxyzzhong** [comment]
目前用的就是`preset-typescript`，可以支持`tsx`文件的，可以查看[示例](https://github.com/ThoughtWorksChina/taro-testing-library/blob/master/src/__tests__/functional-component.test.tsx)。如果需要使用snapshot的话，可以查看[renderToString](https://github.com/ThoughtWorksChina/taro-testing-library#render)方法，这是[nerv-serve](https://github.com/NervJS/nerv-server)提供的渲染snapshot的方法。

**Comment by ariesjia** [comment]
这里有一个[snapshot test demo](https://github.com/ThoughtWorksChina/taro-testing-library/blob/master/src/__tests__/snapshot-component.test.tsx)可以参考这来， `src/__tests__`目录有一些测试可以参考。

**Comment by scarcoco** [comment]
之前的 hook 实现的 counter 没法使用 snapshot，原因是 taro 不支持 hooks？

**Comment by ariesjia** [comment]
没有无法支持，如果不行的给一个示例吧

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: scarcat <notifications@github.com>
发送时间: Wednesday, August 12, 2020 3:50:35 PM
收件人: ThoughtWorksChina/taro-testing-library <taro-testing-library@noreply.github.com>
抄送: Jia Chen <ariesjia00@hotmail.com>; Comment <comment@noreply.github.com>
主题: Re: [ThoughtWorksChina/taro-testing-library] 支持 tsx ？ (#1)


之前的 hook 实现的 counter 没法使用 snapshot，原因是 taro 不支持 hooks？

―
