### ISSUE TITLE
Support for Taro 3.x

### ISSUE THREAD

**Issue by rankun203** [ThoughtWorksChina/taro-testing-library#5]
Question:

Is there any plan for supporting Taro 3.x with React (instead of Nerv)?

**Comment by ariesjia** [comment]
For Taro 3.x and React, I think can use `react-testing-library` directly. 
the only need is to configure `moduleNameMapper` in  `jest.config.js` like this.

```js
{
  moduleNameMapper: {
    '@tarojs/components': '@tarojs/components/dist-h5/react',
    ...
  },
}
```

**Comment by rankun203** [comment]
@ariesjia Thanks for taking your time to respond on this Sunday afternoon.

**Comment by ariesjia** [comment]
It was nothing, hope this information can help you
